#!/bin/sh
# Create initramfs

set -e
trap 'exit' INT QUIT TERM

die() {
	echo "$@" >&2
	exit 1
}

template=$1
version=$2

[ -n "$version" ] || die "Usage: mkinitramfs ramfs-template version"
[ -d "$template" ] || die "Template directory not found: $template"
[ -d "lib/modules/$version" ] || die "Module directory not found: lib/modules/$version"
[ -f modules.ramfs ] || die "List of ramfs modules not found: module.ramfs"

tempdir=$(mktemp -d)
trap 'rm -rf "$tempdir" 2> /dev/null' EXIT

echo "Creating initramfs..."

cp -a "$template"/* "$tempdir"
for dir in bin dev lib mnt mnt/root proc sbin sys tmp; do
	mkdir -p -m 755 "$tempdir/$dir"
done
mkdir -p -m 755 "$tempdir/lib/modules/$version/kernel"
sed -e 's/\s*#.*//' -e '/^\s*$/d' modules.ramfs | xargs tar c -C "lib/modules/$version/kernel" | tar x -C "$tempdir/lib/modules/$version/kernel"
cp -p "lib/modules/$version"/modules.* "$tempdir/lib/modules/$version/"
PATH="$PATH:/usr/sbin:/sbin" depmod -a -b "$tempdir" "$version"
[ -f modules.autoload ] && cp -p modules.autoload "$tempdir"

# create initramfs
{ cd "$tempdir"; find . ! -path . | cut -c 3- | LANG=C sort | cpio -o -R root: --format=newc --quiet; } | gzip -9 > "initramfs-$version"

echo "Initial RAM disk 'initramfs-$version' created"
