#!/bin/sh

# Mount the /proc and /sys filesystems.
mount -t proc none /proc
mount -t sysfs none /sys

# Load default modules
[ -f /modules.autoload ] && xargs -r /sbin/modprobe -a < /modules.autoload

# detect devices
echo > /tmp/prev
for _ in 1 2 3 4 5 6 7 8; do
	find /sys -name modalias | sort > /tmp/cur
	cmp -s /tmp/prev /tmp/cur && break
	comm -13 /tmp/prev /tmp/cur | \
		xargs sort -u | xargs -r /sbin/modprobe -abq
	mv /tmp/cur /tmp/prev
done
rm -f /tmp/prev /tmp/cur

# Update /dev
mdev -s

# Parse kernel cmdline
init=/sbin/init
root=/dev/sda
rdonly=y
single=
while read -r opt; do
	case $opt in
		--)	break ;;
		init=*)	init=${opt#init=} ;;
		root=*)	root=${opt#root=} ;;
		ro)	rdonly=y ;;
		rw)	rdonly= ;;
		single)	single=y ;;
	esac
done << EndOfCmdline
$(split_cmdline < /proc/cmdline)
EndOfCmdline

# Recovery shell
if [ -n "$single" ]; then
	echo "Entering recovery shell..."
	setsid -c ash -i
	echo
	echo "Continuing the boot process..."
fi

# Mount the root filesystem.
[ -z "$rdonly" ] && e2fsck "$root"
mount ${rdonly:+-r} "$root" /mnt/root

# Clean up.
umount /proc
umount /sys

# Boot the real thing.
exec switch_root /mnt/root "$init" "$@"
